name: Python Test Workflow
on: push

jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install
      - name: Run unit tests
        env:
            API_KEY: ${{ secrets.API_KEY }}
            ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        run: |
          pipenv run pytest
